---
title: "Data Import"
output: github_document
---

I'm an R Markdown document! 
```{r}
library(tidyverse)
```

Import a data set.

```{r}
litters_df =
  read_csv("data/FAS_litters.csv")
```
Look at your data!!

```{r}
names(litters_df)
```

Updates the names in 'litters_df'.

```{r}
litters_df = 
  janitor::clean_names(litters_df)
```

Look at the data!!
```{r}
litters_df
view(litters_df)
```

Sometimes skimming data is neat?
```{r}
skimr::skim(litters_df)
```

## Fix the missingness
```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA", ".", ""))
```
Importing pups data set
```{r}
pups_df =
  read_csv(
    "data/FAS_pups.csv", 
    skip = 3,
    na = c("NA", ".", "")
    )

pups_df = 
  janitor::clean_names(pups_df)
```
## What about excel?

CSVs are great but sometimes you get excel.

```{r}
library(readxl)
mlb_df = 
  read_excel("data/mlb11.xlsx")
view(mlb_df)
```

Import LotR word counts.
```{r}
fotr_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```

## SAS??
```{r}
library(haven)
pulse_df =  read_sas("data/public_pulse_data.sas7bdat")

pulse_df = 
  janitor::clean_names(pulse_df)
```

Why do we use read_csv versus read.csv?
Doesn't show as much useful info

```{r eval = FALSE}
litters_df_base = read.csv("data/FAS_litters.csv")
```

Data exporting..
```{r}
write_csv(fotr_df, "data/fotr_df.csv")
```


